version: '2'

services:
    web:
        build: 
            dockerfile: Dockerfile.dev
        image: ${WEB_NAME}:dev
        volumes:
            - ./web:/home
    srv:
        build: 
            dockerfile: Dockerfile.dev
        image: ${SRV_NAME}:dev
        volumes:
            - ./srv:/home
        ports:
            - 3000:3000
            - 5353:5353
    db:
        image: ${DB_NAME}:dev
        volumes:
            - ./!data/db:/data/db